AWSTemplateFormatVersion: '2010-09-09'
Description: 'Dialog Extream CEDGCR Batch Lambda'

Parameters:
  EnvironmentName:
    Type: String
    Description: '[Required] Name of the environment'
    AllowedValues:
      - dev
      - staging

  ArtifactsBucketName:
    Type: String
    Description: 'Name of the bucket created by the Service Catalog Pipeline stack used for Lambda zip storage'
  ZippedLambdaS3Key:
    Type: String
    Description: 'The full S3 path to the location of the zipped Lambda code'
  LambdaRoleName:
    Type: String
    Description: 'The name of the IAM role to be used by the Lambda'

Conditions:
  IsSupportedRegion: !Equals
    - !Sub '${AWS::Region}'
    - ap-south-1

Resources:
  Lambda:
    Condition: IsSupportedRegion
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'dialog-extream-batch-${EnvironmentName}-CEDGCR-Lambda'
      Handler: 'index.handler'
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${LambdaRoleName}'
      Runtime: nodejs20.x
      MemorySize: 1024
      Code:
        S3Bucket: !Ref ArtifactsBucketName
        S3Key: !Ref ZippedLambdaS3Key
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvironmentName
          AWS_ACCOUNT_ID: !Sub '${AWS::AccountId}'
      Timeout: 600
