AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy API Gateway with a POST endpoint to invoke Lambda'

Parameters:
  EnvironmentName:
    Type: String
    Description: '[Required] Name of the environment'
    AllowedValues:
      - dev
      - staging

  ArtifactsBucketName:
    Type: String
    Description: 'S3 bucket storing Lambda zip files'

  ZippedLambdaS3Key:
    Type: String
    Description: 'S3 path of the Lambda zip file'

  LambdaRoleName:
    Type: String
    Description: 'IAM role for Lambda function'

Resources:
  ## 游릭 Lambda Function
  HelloLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'hello-api-${EnvironmentName}'
      Handler: 'index.handler'
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${LambdaRoleName}'
      Runtime: nodejs20.x
      MemorySize: 1024
      Code:
        S3Bucket: !Ref ArtifactsBucketName
        S3Key: !Ref ZippedLambdaS3Key
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvironmentName
      Timeout: 600

  ## 游릭 API Gateway REST API
  HelloApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'hello-api-${EnvironmentName}'
      Description: 'API Gateway for Hello endpoint'

  ## 游릭 API Resource (/hello)
  HelloResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref HelloApi
      ParentId: !GetAtt HelloApi.RootResourceId
      PathPart: hello # This makes the endpoint: /hello

  ## 游릭 POST Method for /hello
  HelloPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref HelloApi
      ResourceId: !Ref HelloResource
      HttpMethod: POST
      AuthorizationType: NONE # No authentication required (modify if needed)
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations'
          - LambdaArn: !GetAtt HelloLambda.Arn

  ## 游릭 Deployment & Stage
  HelloApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: HelloPostMethod
    Properties:
      RestApiId: !Ref HelloApi
      StageName: !Ref EnvironmentName

  ## 游릭 Permission for API Gateway to Invoke Lambda
  LambdaApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref HelloLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HelloApi}/*/POST/hello'

Outputs:
  ## 游릭 API Gateway Invoke URL
  HelloApiInvokeUrl:
    Description: 'Invoke URL for the Hello API'
    Value: !Sub 'https://${HelloApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentName}/hello'
