AWSTemplateFormatVersion: '2010-09-09'
Description: 'The stack for deploying all prerequisite resources for the Code Pipeline stack'

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - T3042

Parameters:
  ApplicationName:
    Type: String
    Description: '[Required] Unique application name'
    AllowedPattern: '.+'
  EnvironmentName:
    Type: String
    Description: '[Required] Name of the environment'
    Default: 'tbv'
    AllowedValues:
      - 'dev'
      - 'stg'
      - 'prod'
  DataClassification:
    Type: String
    Description: 'Data Classification'
    Default: GroupUse
    AllowedValues: [GroupUse, Public, Confidential, CustomerPersonal, HighlyProtected]

Mappings:
  S3ProductParameters:
    default:
      ProductName: 'BP-S3-Product'
      ProvisioningArtifactName: '1.0.0'

Conditions:
  IsSupportedRegion: !Equals
    - !Ref 'AWS::Region'
    - 'ap-south-1'

Resources:
  ArtifactsBucketStack:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: !FindInMap [S3ProductParameters, 'default', 'ProductName']
      ProvisioningArtifactName: !FindInMap [S3ProductParameters, 'default', 'ProvisioningArtifactName']
      ProvisioningParameters:
        - Key: 'NodeName'
          Value: !Sub '${ApplicationName}-artifacts_bucket'
        - Key: 'DataClassification'
          Value: !Ref DataClassification
  CertificateBucketStack:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: !FindInMap [S3ProductParameters, 'default', 'ProductName']
      ProvisioningArtifactName: !FindInMap [S3ProductParameters, 'default', 'ProvisioningArtifactName']
      ProvisioningParameters:
        - Key: 'NodeName'
          Value: !Sub '${ApplicationName}-certificate_bucket'
        - Key: 'DataClassification'
          Value: !Ref DataClassification
  ArtifactsBucketNameSsmParameter:
    Type: AWS::SSM::Parameter
    Condition: IsSupportedRegion
    Properties:
      Name: !Sub '/${ApplicationName}/artifacts_bucket'
      Description: 'Stores the name of the artifacts bucket that has all ASM infra templates and the ec2 user data script etc.'
      Value: !GetAtt ArtifactsBucketStack.Outputs.S3BucketName
      Type: String
      Tags:
        DataClassification: !Ref DataClassification
  CertificateBucketNameSsmParameter:
    Type: AWS::SSM::Parameter
    Condition: IsSupportedRegion
    Properties:
      Name: !Sub '/${ApplicationName}/certificate_bucket'
      Description: 'Stores the name of the certificate bucket'
      Value: !GetAtt CertificateBucketStack.Outputs.S3BucketName
      Type: String
      Tags:
        DataClassification: !Ref DataClassification
  ArtifactsWebsiteNameSsmParameter:
    Type: AWS::SSM::Parameter
    Condition: IsSupportedRegion
    Properties:
      Name: !Sub '/${ApplicationName}/website_name'
      Description: 'Stores the name of the Website'
      Value: !Ref WebsiteName
      Type: String
      Tags:
        DataClassification: !Ref DataClassification

Outputs:
  ArtifactsBucketName:
    Condition: IsSupportedRegion
    Description: 'Artifacts bucket name'
    Value: !GetAtt ArfitactsBucketStack.Outputs.S3BucketName
    Export:
      Name: !Sub ${ApplicationName}-${EnvironmentName}-artifacts-bucket-name
