version:0.2

phases:
  install:
    runtime-versions:
      nodejs:20
  pre_build:
    commands:
      -npm ci
  build:
    commands:
      -npm run lint
      -npm run test
      -npm run build
artifacts:
  files:'**/*'