version: 0.2

variables:
  ENVIRONMENT: $ENVIRONMENT

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - chmod +x .code-pipeline/deploy-stage-2.sh
      - bash .code-pipeline/deploy-stage-2.sh --environment $ENVIRONMENT --application-name my-batch-lambdas --debug true

artifacts:
  files:
    - '*/'
