name: CI and Deploy Lambdas

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  deployLambdas:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: dev
      APPLICATION_NAME: my-batch-lambdas
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1

    steps:
      - name: Build
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

        uses: actions/setup-node@v4
        with:
          node-version: 20

        run: |
          npm install && \
          npm run lint && \
          npm run test && \
          npm run build

      - name: Deploy
        run: |
          chmod +x .code-pipeline/deploy-stage-2.sh && \
          bash .code-pipeline/deploy-stage-2.sh --environment ${{ env.ENVIRONMENT }} --application-name ${{ env.APPLICATION_NAME }} --debug true



